### ISSUE TITLE
Deployment problem using build.cmd 

### ISSUE THREAD

**Issue by ermhawi** [Azure/azure-iot-remote-monitoring#4]
Hi,

I am trying to deploy this project using the "build.cmd cloud" command but in the end I get an error message about the "ServiceConfiguration.Cloud.cscfg" file. I can not find this file anywhere in the repository. Any idea why?

2015-10-08T11:04:19.1032114+02:00 - Executing New-AzureDeployment -Slot Staging -Package C:\Users\hakan\Source\Repos\azure-iot-remote-monitoring\Build_Output\debug\Services\Simulator\pub\Simulator.cspkg -Configuration C:\Users\hakan\Source\Repos\azure-iot-remote-monitoring\Build_Output\debug\Services\Simulator\pub\ServiceConfiguration.Cloud.cscfg -label "AutoDeploy 2015-10-08T11:03:20.3712325+02:00" -ServiceName remotemon1Simulator

Could not find a part of the path 'C:\Users\hakan\Source\Repos\azure-iot-remote-monitoring\Build_Output\debug\Services\Simulator\pub\Simulator.cspkg'.
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : Could not find a part of the path 'C:\Users\hakan\Source\Repos\azure-iot-remote-monitoring\Build_Output\debug\Services\Simulator\pub\Simulator.cspkg'.
    + PSComputerName        : localhost

**Comment by networkfusion** [comment]
I am also receiving this error. I am guessing it has something to do with the depreciation of "SwitchAzureMode" https://github.com/Azure/azure-powershell/wiki/Deprecation-of-Switch-AzureMode-in-Azure-PowerShell as further up the script execution there is a warning and then an error relating to building the cspkg's. I am guessing that this is due to having a newer version of the toolchain installed...

are there any workarounds for this as I have spent most of the day getting this far (so much for ease of deployment - documentation in this area seriously needed).

**Comment by aguilaaj** [comment]
All, take a look at https://github.com/Azure/azure-iot-remote-monitoring/issues/2 for the time being.

**Comment by stevehoberecht** [comment]
We've done some work to the build.cmd and will be pushing that up soon.  In the meantime, you can deploy using the following steps:

Open Azure Powershell to perform the following set of commands

- Change to the location of the source repository
	- `>cd ..\somepath\azure-iot-remote-monitoring`
- Login within Azure Powershell with the command:
	- `Add-AzureAccount` 
- If you have multiple subscriptions (or don't know and want to check), check and select the subscription with the following commands:
	- `Get-AzureSubscription -current`
	- `Select-AzureSubscription -subscriptionid <id-you-want-to-use>`
- Switch AzureMode with the command: 
	- `Switch-AzureMode AzureResourceManager`
- Create a resource group to contain your solution with the command:
	- *If the resource group already exists, you can skip this step*
	- `New-AzureResourceGroup -name <YourRGName> -location <Valid Region>`
- Deploy your solution with the command:
	- `New-AzureResourceGroupDeployment -name <YourSolutionName> -resourcegroupname <YourRGName> -templatefile .\Common\Deployment\RemoteMonitoring.json -aadtenant <TenantId> –verbose`

There are a couple of changes being made to services deployment.  Stream Analytics jobs don't start by default.  To work around this, once the deployment steps above are completed, perform the following 4 steps in the Azure management portal.

- Start stream analytics job: `<solution name>-DeviceInfo`
- Start stream analytics job: `<solution name>-Telemetry`
- Start stream analytics job: `<solution name>-Rules`
- Re-start web site: `stop/start`

**Comment by networkfusion** [comment]
@stevehoberecht thanks, that has allowed deployment to complete successfully and I can now get to the login page, however I am now getting an error when trying to authenticate: 

Application with identifier 'https://<mywebsitename>.azurewebsites.net/iotsuite' was not found in the directory <mytennantid>

is there something else that needs manual setup within AAD?

**Comment by stevehoberecht** [comment]
Correct.  This will allow access for AAD tenant admins.  If you want to create and use the two roles the remote monitoring solution has (Admin, ReadOnly), here is how to configure those in AAD.

### Setting up roles and assigning permissions in Azure Active Directory (AAD)

#### Creating the Application
- Go to AzurePortal:  [https://manage.windowsazure.com](manage.windowsazure.com)
- Navigate the the Active Directory section and select the directory in which you created your solution.
- Go to ‘Applications’; in the ‘show’ drop-down, select “Applications my company owns”
- At the bottom of the page, click “Add”; select to “Add an application my organization is developing”
- Name the application and select the type: “Web application and/or web API”
- For Application properties enter the following:
	- Sign-on URL: `https://<yoursolutionname>.azurewebsites.net`
	- App ID URL: `https://<yoursolutionname>.azurewebsites.net/iotsuite`
- You will see a quick start indicating your app has been added

#### Create Roles for the Application
- At the bottom of the page, select “manage manifest” -> “download manifest”
- This will download a .json file locally.  Open the file for editing (in the text editor of your choice).
- In the third line of the .json file, you will see:
	- `"appRoles" : [],`
	- Replace this with the following:
	
    "appRoles": [
    {
    "allowedMemberTypes": [
    "User"
    ],
    "description": "Administrator access to the application",
    "displayName": "Admin",
    "id": "a400a00b-f67c-42b7-ba9a-f73d8c67e433",
    "isEnabled": true,
    "value": "Admin"
    },
    {
    "allowedMemberTypes": [
    "User"
    ],
    "description": "Read only access to device information",
    "displayName": "Read Only",
    "id": "e5bbd0f5-128e-4362-9dd1-8f253c6082d7",
    "isEnabled": true,
    "value": "ReadOnly"
    } ],
- Save the updated .json file (it's ok to overwrite)
- Back in the Azure Management Portal, at the bottom of the page, select "manage manifest" -> "upload manifest"
- Upload the .json file you just saved

You have now created two roles for your application:  Admin and ReadOnly

#### Assigning users to the roles

- In the Active Directory page for your application, go to "Users and Groups"
- Select yourself (or other listed user) and on the bottom of the page, select "Assign"
- This will prompt you with a drop down of the roles (Admin, ReadOnly)
- Choose the appropriate group for the user

You now have granted the selected user rights to your remote monitoring solution.  The ReadOnly group will be able to see the dashboard and the device list, but will not be allowed to add devices, change device attributes, or send commands.  Members of the Admin group will have full permissions to all the functionality of the solution.

**Comment by networkfusion** [comment]
@stevehoberecht thanks, I figured out the user roles about 10 mins before you posted! 

Wouldn't it be better to add this information to readme.md or the wiki, even if it was only a temporary thing?

Also 2 last questions if I may
1: what is the best way to upload changes to the source as I plan to start customising soon...
2: any particular reason I would be receiving the error "Unable to receive alerts history from the service" about every 3 seconds when in the dashboard view or should I open another issue about this?!

**Comment by jamesweb-ms** [comment]
I have just pushed the initial rewrite/cleanup for using templates to branch jamesweb-dev.  Feel free to try it for both local dev and cloud deployments.  A note on cloud deployments, the Stream analytic jobs do not currently start during deployment and expect them to be in stopped state before deploying again.  This is a manual step until next week when the SAS team will deploy a feature that will allow us to control the state from the provisioning template.

Please do let me know if you run into any issues or have feedback.

**Comment by networkfusion** [comment]
@jamesweb-ms Thanks, I am deploying now with your branch and build.cmd. I have received an error:

git : The term 'git' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\Pr
epareIoTSample.ps1:30 char:26
+     [string]$branch = "$(git symbolic-ref --short -q HEAD)"
+                          ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException

but will let you know if this causes any problems as it is still deploying.

**Comment by networkfusion** [comment]
selected no on the message: Provided resource group already exists. Are you sure you want to update it? and it still continued to deploy, is this the correct behaviour?


as the first deployment failed with a few errors, I deleted all resources and started again.

I still receive the git error and also get an error related to blob storage:

Deployment template path: C:\Users\Robin\Source\Repos\azure-iot-remote-monitorin
g\Common\Deployment\RemoteMonitoring.json
Set-AzureStorageBlobContent : The remote name could not be resolved:
'surfacenet.blob.core.windows.net'
At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\De
ploymentLib.ps1:297 char:13
+     $null = Set-AzureStorageBlobContent -Blob $fileName -Container $C ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], S
   torageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands
   .Storage.Blob.SetAzureBlobContentCommand

Set-AzureStorageBlobContent : The remote name could not be resolved:
'surfacenet.blob.core.windows.net'
At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\De
ploymentLib.ps1:297 char:13
+     $null = Set-AzureStorageBlobContent -Blob $fileName -Container $C ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Set-AzureStorageBlobContent], S
   torageException
    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands
   .Storage.Blob.SetAzureBlobContentCommand


I also received the following error whiched stopped the provisioning from completing:

VERBOSE: 21:38:20 - Resource Microsoft.Web/sites/extensions
'surfacenet/MSDeploy' provisioning status is running
New-AzureResourceGroupDeployment : 21:38:27 - Resource
Microsoft.Web/sites/extensions 'surfacenet-jobhost/MSDeploy' failed with
message 'The resource operation completed with terminal provisioning state
'Failed'.'
At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\Pr
epareIoTSample.ps1:74 char:11
+ $result = New-AzureResourceGroupDeployment -ResourceGroupName $resour ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureResourceGroupDeploym
   ent], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou
   rceGroupDeploymentCommand

New-AzureResourceGroupDeployment : 21:38:27 - Resource
Microsoft.Web/sites/extensions 'surfacenet/MSDeploy' failed with message 'The
resource operation completed with terminal provisioning state 'Failed'.'
At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\Pr
epareIoTSample.ps1:74 char:11
+ $result = New-AzureResourceGroupDeployment -ResourceGroupName $resour ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-AzureResourceGroupDeploym
   ent], Exception
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Resources.NewAzureResou
   rceGroupDeploymentCommand

Provisioing failed
At C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\Common\Deployment\Pr
epareIoTSample.ps1:79 char:5
+     throw "Provisioing failed"
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Provisioing failed:String) []
   , RuntimeException
    + FullyQualifiedErrorId : Provisioing failed

Error C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy
 Unrestricted -Command C:\Users\Robin\Source\Repos\azure-iot-remote-monitoring\\
Common\Deployment\PrepareIoTSample.ps1 -environmentName surfacenet -configuratio
n release


also, should be able to select subscription by list
should be able to select region by list

hope all of that makes sense.

I am out of the country until next weekend so not sure how technology will cope. If it is bad then I will continue testing next weekend.

**Comment by networkfusion** [comment]
@jamesweb-ms  ok, after receiving the above errors and rerunning build.cmd multiple times, it says everything has installed successfully. However no simulator worker role has been installed, is this to be expected?

When deploying the iothub it allocates the s2 pricing plan, would it be better to select s1 (free)? in fact the same for all deployed services as it is burning through my azure credit!

**Comment by jamesweb-ms** [comment]
The git command was left over from trying to do git deploy (we need to do some work to support that).  I will remove from now, and figure how to make sure that dependency is resolved correctly.

The other issues you were having all appear to be DNS related issues.  I was seeing DNS issues Friday night, so depending on when you tried you might have run into the same issue.  I will do some more testing and add some defensive code in there to make sure we get a good error.

As for the final deployment, you should have two web deployments, one with a website, one with a web job.  @stevehoberecht can you address why we have separated out the roles and switched to S2?

**Comment by jamesweb-ms** [comment]
Some more notes that I will document:

also, should be able to select subscription by list
should be able to select region by list

- first time it runs it prompts for both of these.  It saves the response in *.config.user files in you repo root, along with keys used by the services when running locally under the debugger.  You can always change the files directly, but once deployed you can't change region.  Subscription is also not likely as it requires ARM support for Move which is not widely available yet.

**Comment by networkfusion** [comment]
@jamesweb-ms in regards to:
also, should be able to select subscription by list
 should be able to select region by list

I should have been more clear... for example, if the question was 
"Please select a region from the list:
1) West US
2) North Europe
...
"

The same for subscription. I am sure this is how it works in the connectthedots config script... this means that the input is less prone to error.

Also the bing maps API always gets associated with west us. Is this not available in other regions?

**Comment by jamesweb-ms** [comment]
Regarding regions, that makes sense.  I will display available regions before prompting.

As to Bing Maps, they currently have a single region available, but it works world wide.  We checked with them and they were fine using West for global deployments.

**Comment by jamesweb-ms** [comment]
oops, wrong button....  will close issue once we've merged to Master.  Fix is currently in October-Integration.

**Comment by jamesweb-ms** [comment]
This issue is now resolved in master
